<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Login</title>
</head>
<body>

    <h2>Customer Login</h2>
    
    <form action="<?php echo $this->getUrl("*/*/loginCustomer")?>" method="POST">
        <label for="email">Email:</label>
        <input type="email" id="email" name="customer[email]" required>
        <br><br>

        <label for="password">Password:</label>
        <input type="password" id="password" name="customer[password]" required>
        <br><br>

        <button type="submit">Login</button>
    </form>
    <a href="<?php echo $this->getUrl('*/*/register') ?>">Login here</a>
</body>
</html>
