<!DOCTYPE html>
<html lang="en">
<?php
$data = $this->getAttributes();

$categories = $this->getCategoryData();
$productData = $this->getProductData()[0];
$image_data = $this->getProductData()[1];
// echo "<pre>";
// print_r($productData);
?>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Form</title>
</head>

<body>
    <h2>Product Form</h2>
    <form method="post" action="<?php echo $this->getUrl('*/*/save'); ?>" enctype="multipart/form-data">
        <input type="hidden" name="catalog_product[product_id]" value="<?php echo $productData->getProductId(); ?>">
        <label for="name">Name:</label>
        <input type="text" id="name" name="catalog_product[name]" required maxlength="255"
            value="<?php echo $productData->getName(); ?>"><br><br>

        <label for="description">Description:</label>
        <textarea id="description"
            name="catalog_product[description]"><?php echo $productData->getDescription(); ?></textarea><br><br>

        <label for="price">Price:</label>
        <input type="number" id="price" name="catalog_product[price]" required step="0.01"
            value="<?php echo $productData->getPrice(); ?>"><br><br>

        <label for="stock_quantity">Stock Quantity:</label>
        <input type="number" id="stock_quantity" name="catalog_product[stock_quantity]"
            value="<?php echo $productData->getStockQuantity() ?>"><br><br>

        <label for="category_id">Category:</label>
        <select id="category_id" name="catalog_product[category_id]">
            <option value="">Select Category</option>
            <?php foreach ($categories as $_category): ?>
                <option value="<?= $_category->getCategoryId(); ?>"
                    <?= ($_category->getCategoryId() == $productData->getCategoryId()) ? 'selected' : ''; ?>>
                    <?= $_category->getName(); ?>
                </option>
            <?php endforeach; ?>
        </select><br><br>
        <?php
        foreach ($data as $_data) {
            $method = "get" . ucfirst($_data->getName());
            // print_r($method);
            // echo $_data->$method();
        ?>
            <label for="<?php echo $_data->getattributeId(); ?>"><?php echo $_data->getname(); ?>:</label>
            <input type="<?php echo $_data->gettype() ?>" value="<?php echo $productData->$method(); ?>"
                name="catalog_product[<?php echo $_data->getname(); ?>]">
            <br>
            <br>
        <?php
        }
        ?>

        <label for="images">Upload Images:</label>
        <input type="file" id="images" name="catalog_product[images][]" multiple accept="image/*" oninput="test()"><br><br>
        <div id="img_div" style="display: none;">

        </div>
        <button type="submit">Submit</button>
    </form>
    <div>
        <?php
        foreach($image_data as $image):?>
        <?php $path= Mage::getBaseUrl()."Media/Catalog_Product/".$image->getFilePath();?>
        <img src="<?php echo $path;?>" height="100" width="100">
        <?php endforeach;?>
    </div>
    <script>
        function test() {

            document.getElementById("img_div").innerHTML = "";
            var img_data = "";
            var img = document.getElementById("images").files;
            for (var i = 0; i < img.length; i++) {
                img_data +=
                    "<label><input type='radio' name='catalog_product[main_image]' value='" + img[i].name + "'> " + img[i].name + "</label><br>";
            }
            document.getElementById("img_div").innerHTML = img_data;
            document.getElementById("img_div").style.display = "block";
        }
    </script>
</body>

</html>