<!DOCTYPE html>
<html lang="en">
<?php
$data = $this->getAttributes();

$categories = $this->getCategoryData();
$productData = $this->getProductData();
// echo "<pre>";
// print_r($productData);
?>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Form</title>
</head>

<body>
    <h2>Product Form</h2>
    <form method="post" action="<?php echo $this->getUrl('*/*/save'); ?>" enctype="multipart/form-data">
        <input type="hidden" name="catalog_product[product_id]" value="<?php echo $productData->getProductId(); ?>">
        <label for="name">Name:</label>
        <input type="text" id="name" name="catalog_product[name]" required maxlength="255"
            value="<?php echo $productData->getName(); ?>"><br><br>

        <label for="description">Description:</label>
        <textarea id="description" name="catalog_product[description]"><?php echo $productData->getDescription(); ?></textarea><br><br>

        <label for="price">Price:</label>
        <input type="number" id="price" name="catalog_product[price]" required step="0.01"
            value="<?php echo $productData->getPrice(); ?>"><br><br>

        <label for="stock_quantity">Stock Quantity:</label>
        <input type="number" id="stock_quantity" name="catalog_product[stock_quantity]" value="<?php echo $productData->getStockQuantity() ?>"><br><br>

        <label for="category_id">Category:</label>
        <select id="category_id" name="catalog_product[category_id]">
            <option value="">Select Category</option>
            <?php foreach ($categories as $_category): ?>
                <option value="<?= $_category->getCategoryId(); ?>"
                    <?= ($_category->getCategoryId() == $productData->getCategoryId()) ? 'selected' : ''; ?>>
                    <?= $_category->getName(); ?>
                </option>
            <?php endforeach; ?>
        </select><br><br>

        <?php
        foreach ($data as $_data) {
            $method = "get" . $_data->getName();
        ?>
            <label for="<?php echo $_data->getattributeId(); ?>"><?php echo $_data->getname(); ?>:</label>
            <input type="<?php echo $_data->gettype() ?>" value="<?php echo $productData->$method(); ?>" name="catalog_product_attribute[<?php echo $_data->getname(); ?>]">
            <br>
            <br>
        <?php
        }
        ?>
        <label for="images">Upload Other Images:</label>
        <input type="file" id="images" name="catalog_media_gallery[images][]" multiple accept="image/*"><br><br>
        <button type="submit">Submit</button>
    </form>

</body>

</html>