<!DOCTYPE html>
<html lang="en">


<?php
$data = $this->getProdData();

?>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Form</title>
    <style>
    body {
        font-family: Arial, sans-serif;
        background-color: #dcdcdc;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .form-container {
        background: #ffffff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        width: 400px;
    }

    .form-group {
        margin-bottom: 15px;
        margin-right: 10px;
    }

    label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
        color: #34495e;
    }

    input,
    textarea,
    select {
        width: 100%;
        padding: 10px;
        border: 1px solid #bdc3c7;
        border-radius: 4px;
        background-color: #ffffff;
    }

    button {
        background-color: #2980b9;
        color: white;
        padding: 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
        font-size: 16px;
        font-weight: bold;
    }

    button:hover {
        background-color: #1f6691;
    }
    </style>
</head>

<body>
    <div class="form-container">
        <form method="POST" enctype="multipart/form-data" action="<?php echo $this->getUrl('*/*/save'); ?>">
            <?php if (!empty($data)): ?>
            <?php echo $data->getProductId(); ?>
            <div class="form-group">

                <input type="hidden" id="product_id" name="catlog_product[product_id]"
                    value=<?php echo $data->getProductId(); ?>>
               
            </div>
            <?php endif; ?>
            <div class="form-group">


            <?php echo $this->getHtmlField("number",["min"=>1,"max"=>10,"id"=>"n1","value"=>$data->getProductId()]);?>
                <label for="name">Name:</label>
                <?php 
                echo $this->getHtmlField("text",["id"=>"ni","class"=>"sarg","value"=>$data->getName()]);
                ?>
                <!-- <input type="text" id="name" name="catlog_product[name]" value=<?php echo $data->getName(); ?>> -->
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                <textarea id="description" name="catlog_product[description]" value=""
                    required><?php echo $data->getdescription(); ?></textarea>
            </div>
            <div class="form-group">
                <label for="price">Price:</label>
                <input type="number" id="price" name="catlog_product[price]" value="<?php echo $data->getprice(); ?>"
                    required>
            </div>
            <div class="form-group">
                <label for="image">Image:</label>
                <input type="file" id="image" name="catlog_product[image]" accept="image/*"
                    value="<?php echo $data->getProductImage(); ?>">
                <?php
                if (!empty($data) && !empty($data->getImage())) {
                    $image_path = "/MVC/Media/catlog_product/" . $data->getImage();
                ?>
                <img src="<?php echo $image_path; ?>" height="100" width="100">
                <?php
                }
                ?>

            </div>
            <div class="form-group">
                <label for="rating">Rating (0 to 5):</label>
                <input type="range" id="rating" name="catlog_product[rating]" min="0" max="5" step="0.1"
                    value="<?php echo $data->getrating(); ?>">
            </div>
            <div class="form-group">
                <label for="color">Color:</label>
                <input type="text" id="color" name="catlog_product[color]" value="<?php echo $data->getcolor(); ?>"
                    required>
            </div>
            <div class="form-group">
                <label for="size">Size:</label>
                <input type="number" id="size" name="catlog_product[size]" value="<?php echo $data->getsize(); ?>"
                    required>
                <div class="form-group">
                    <label for="brand">Brand:</label>
                    <input type="text" id="brand" name="catlog_product[brand]"
                        value="<?php echo ($data->getBrand()); ?>" required>
                </div>
                <div class="form-group">
                    <label for="category">Category Name:</label>
                    <select id="category" name="catlog_product[category_id]" required>
                        <?php
                        $selectedCategoryId = $data->getCategoryId();
                        foreach ($this->cat_data as $catdata):
                            $categoryId = $catdata->getCategoryId();
                            $selected = ($categoryId == $selectedCategoryId) ? 'selected' : '';
                        ?>
                        <option value="<?php echo $categoryId; ?>" <?php echo $selected; ?>>
                            <?php echo ($catdata->getName()); ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="warranty">Warranty (years):</label>
                    <input type="number" step="0.1" id="warranty" name="catlog_product[warranty]"
                        value="<?php echo $data->getwarranty(); ?>" required>
                </div>
                <div class="form-group">
                    <label for="weight">Weight (kg):</label>
                    <input type="number" step="0.1" id="weight" name="catlog_product[weight]"
                        value="<?php echo $data->getweight(); ?>" required>
                </div>
                <div class="form-group">
                    <label for="made_in">Made In:</label>
                    <select id="made_in" name="catlog_product[made_in]" required>
                        <option value="">Select Country</option>
                        <option value="india" selected>India</option>
                        <option value="china">China</option>
                        <option value="usa">USA</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="model">Model:</label>
                    <input type="text" id="model" name="catlog_product[model]" value="<?php echo $data->getmodel(); ?>"
                        required>
                </div>
                <div class="form-group">
                    <label for="mfg_date">Manufacturing Date:</label>
                    <input type="date" id="mfg_date" name="catlog_product[mfg_date]"
                        value="<?php echo $data->getMfgDate(); ?>" required>
                </div>
                <div class="form-group">
                    <label for="material">Material:</label>
                    <input type="text" id="material" name="catlog_product[material]"
                        value="<?php echo $data->getMaterial(); ?>" required>
                </div>
                <div class="form-group">
                    <label for="terms">Terms and Conditions:</label>
                    <textarea id="terms" name="catlog_product[t_and_c]" required><?php
                                                                                    echo $data->getTAndC();
                                                                                    ?></textarea>
                </div>
                <div class="form-group">
                    <label for="made_in">Product Status</label>
                    <select id="made_in" name="catlog_product[product_status]" required>
                        <option value="1" selected>Enable</option>
                        <option value="0">Disable</option>
                        
                    </select>
                </div>
                <button type="submit">Submit</button>
        </form>
    </div>
</body>

</html>