<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Category listing page</h1>
    <?php
    $data = $this->listCatdata();
    //print_r($data);
    ?>
    <table border=5 cellspacing=5px cellpadding=10px>
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Parent Category Name</th>
            <th>created at</th>
            <th>Updated at</th>
        </thead>
        <tbody>
            <?php foreach ($data as $data): ?>
                <tr>
                    <td><?php echo $data->getCategoryId(); ?></td>
                    <td><?php echo $data->getName(); ?></td>
                    <td><?php echo $data->getDescription(); ?></td>
                    <td><?php echo $data->getParentId(); ?></td>
                    <td><?php echo $data->getCreatedAt(); ?></td>
                    <td><?php echo $data->getUpdatedAt(); ?></td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>

</html>