<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    <!-- <link rel="stylesheet" href="styles.css"> -->
    <style>
    </style>
</head>
<body class="login-page">
    <div class="login-container">
        <h2>Login</h2>
        <form method="POST" action="<?php echo $this->getUrl('*/*/loginPost'); ?>">
            <div class="input-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="user[username]" required>
            </div>
            <div class="input-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="user[password]" required>
            </div>
            <input type="submit">
            <!-- <button type="submit" class="login-btn">Login</button> -->
        </form>
    </div>
</body>

</html>