<head>
<?php
$js=$this->getJs();
$css=$this->getCss();
$base_url=Mage::getBaseUrl();

foreach($css as $css)
{
    ?>
    <link href="<?php echo $base_url . $css;?>" rel="stylesheet"></link>
    <?php
}
?>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<!-- <script type="text/javascript">
    // alert("1");
    //  var filter=
    // {
    //     // alert("2");
    //     xyz:function ()
    //    {
    //    this.p=20
    //     alert("in xyz");
    //    },
    //    abc:function()
    //    {
    //     alert(this.p);
    //    } 
    //     // return this;
    // }
    // filter.xyz();
    // filter.abc();
    </script> -->
</head>